<?php
/**
 * Wires up the chat REST routes and the frontend widget. Called explicitly
 * from Module::boot() once this wave is integrated (not auto-registered here,
 * so it can land independently of that change).
 *
 * @package UxStudio
 */

namespace UxStudio\Modules\AiAssistant;

use UxStudio\Core\Settings;

defined( 'ABSPATH' ) || exit;

final class ChatBootstrap {

	/**
	 * Registers the chat REST controller and, on the frontend only, the
	 * widget assets - gated by the "widget_enabled" setting.
	 */
	public static function register(): void {
		add_action( 'rest_api_init', array( self::class, 'register_rest_routes' ) );

		if ( self::widget_enabled() ) {
			add_action( 'wp_enqueue_scripts', array( self::class, 'enqueue_widget_assets' ) );
			add_action( 'wp_footer', array( self::class, 'render_widget_root' ) );
		}
	}

	public static function register_rest_routes(): void {
		( new ChatRestController() )->register_routes();
	}

	private static function widget_enabled(): bool {
		return (bool) ( new Settings( 'uxstudio_ai_assistant' ) )->get( 'widget_enabled', true );
	}

	/**
	 * Enqueues only a ~2 kB deferred loader plus a few lines of inline CSS for
	 * the bubble. The full widget (JS + CSS, minified unless SCRIPT_DEBUG) is
	 * fetched by the loader on the first interaction with the bubble - see
	 * assets/js/ai-assistant-widget-loader.js. Minified files are generated by
	 * `npm run build:widget` from the unminified sources next to them.
	 */
	public static function enqueue_widget_assets(): void {
		if ( is_admin() ) {
			return;
		}

		$suffix     = ( defined( 'SCRIPT_DEBUG' ) && SCRIPT_DEBUG ) ? '' : '.min';
		$css_rel    = self::asset( 'assets/css/ai-assistant-widget', $suffix, 'css' );
		$js_rel     = self::asset( 'assets/js/ai-assistant-widget', $suffix, 'js' );
		$loader_rel = self::asset( 'assets/js/ai-assistant-widget-loader', $suffix, 'js' );

		$version = (string) max(
			self::mtime( $css_rel ),
			self::mtime( $js_rel ),
			self::mtime( $loader_rel )
		);
		if ( '0' === $version ) {
			$version = defined( 'UXSTUDIO_VERSION' ) ? UXSTUDIO_VERSION : '1.0.0';
		}

		wp_register_style( 'uxstudio-ai-assistant-bubble', false, array(), $version );
		wp_enqueue_style( 'uxstudio-ai-assistant-bubble' );
		wp_add_inline_style( 'uxstudio-ai-assistant-bubble', self::bubble_css() );

		wp_enqueue_script(
			'uxstudio-ai-assistant-widget',
			UXSTUDIO_URL . $loader_rel,
			array(),
			$version,
			array(
				'in_footer' => true,
				'strategy'  => 'defer',
			)
		);

		$settings = new Settings( 'uxstudio_ai_assistant' );
		$language = (string) $settings->get( 'language', 'cs' );
		if ( ! in_array( $language, array( 'cs', 'en' ), true ) ) {
			$language = 'cs';
		}

		$product_id = 0;
		if ( function_exists( 'is_product' ) && is_product() ) {
			$product_id = get_the_ID() ?: 0;
		}

		wp_localize_script(
			'uxstudio-ai-assistant-widget',
			'uxstudioAiAssistantWidget',
			array(
				'restUrl'          => esc_url_raw( rest_url( 'uxstudio/v1/ai-assistant' ) ),
				'nonce'            => wp_create_nonce( 'wp_rest' ),
				'productId'        => $product_id,
				'maxMessageLength' => ChatRestController::MAX_MESSAGE_LENGTH,
				'openLabel'        => 'cs' === $language ? 'Otevřít chat' : 'Open chat',
				'assets'           => array(
					'js'  => add_query_arg( 'ver', $version, UXSTUDIO_URL . $js_rel ),
					'css' => add_query_arg( 'ver', $version, UXSTUDIO_URL . $css_rel ),
				),
				'config'           => array(
					'type'               => 'bubble',
					'position'           => 'bottom-right',
					'color'              => '#2271b1',
					'textColor'          => '#ffffff',
					'title'              => PromptTemplates::default_title( $language ),
					'greeting'           => PromptTemplates::default_greeting( $language ),
					'placeholder'        => PromptTemplates::default_placeholder( $language ),
					'gdprText'           => PromptTemplates::default_gdpr_text( $language ),
					'autoOpen'           => false,
					'autoOpenDelay'      => 5,
					'autoOpenSound'      => true,
					'autoOpenCooldown'   => 30,
					'inactivityTimeout'  => 60,
				),
			)
		);
	}

	public static function render_widget_root(): void {
		echo '<div id="uxstudio-ai-assistant-widget-root"></div>';
	}

	/**
	 * Relative path of the minified asset, falling back to the unminified
	 * source when the .min file has not been built.
	 */
	private static function asset( string $base, string $suffix, string $ext ): string {
		$rel = $base . $suffix . '.' . $ext;
		return ( '' !== $suffix && ! file_exists( UXSTUDIO_PATH . $rel ) ) ? $base . '.' . $ext : $rel;
	}

	private static function mtime( string $rel ): int {
		$path = UXSTUDIO_PATH . $rel;
		return file_exists( $path ) ? (int) filemtime( $path ) : 0;
	}

	/**
	 * Just enough CSS to draw the placeholder bubble before the full widget
	 * stylesheet is loaded (mirrors .uxstudio-ais-trigger in ai-assistant-widget.css).
	 */
	private static function bubble_css(): string {
		return '#uxstudio-ai-assistant-widget-root .uxstudio-ais-trigger--placeholder{position:fixed;bottom:24px;right:24px;z-index:99999;width:56px;height:56px;min-height:0;margin:0;padding:0;border:none;border-radius:50%;'
			. 'background-color:var(--uxstudio-ais-color,#2271b1);color:var(--uxstudio-ais-text,#fff);box-shadow:0 4px 14px rgba(0,0,0,.2);cursor:pointer;display:flex;align-items:center;justify-content:center;-webkit-tap-highlight-color:transparent}'
			. '#uxstudio-ai-assistant-widget-root .uxstudio-ais-trigger--placeholder.uxstudio-ais-trigger--left{right:auto;left:24px}'
			. '#uxstudio-ai-assistant-widget-root .uxstudio-ais-trigger--placeholder svg{width:26px;height:26px;fill:currentColor;flex-shrink:0}'
			. '@media print{#uxstudio-ai-assistant-widget-root{display:none!important}}';
	}
}
