/**
 * Maps a module's kebab-case icon name (from its meta.json `icon` field) to the
 * matching lucide-react component. Only the icons actually referenced by the
 * shipped modules are imported, so tree-shaking keeps the bundle small (no
 * `import *` of the whole lucide set).
 *
 * When a module declares an icon not listed here, <ModuleIcon> falls back to
 * Puzzle. If you add a module with a new icon, add its mapping below.
 */
import type { ComponentType } from 'react';
import {
	Activity,
	ArrowUpDown,
	Bell,
	BellRing,
	BookOpen,
	Bot,
	Bug,
	CalendarOff,
	Clock,
	Code,
	Construction,
	Copy,
	CornerUpLeft,
	ExternalLink,
	Eye,
	EyeOff,
	FileCode,
	FileDown,
	FileText,
	Folder,
	FolderOpen,
	Gauge,
	Hash,
	History,
	Image,
	ImageDown,
	ImageMinus,
	ImagePlus,
	Images,
	Import,
	Inbox,
	Instagram,
	LayoutDashboard,
	LayoutGrid,
	Link,
	LogIn,
	Mail,
	MailCheck,
	MailOpen,
	MessageSquare,
	PanelTop,
	Puzzle,
	RefreshCw,
	RefreshCwOff,
	Replace,
	SearchX,
	Shield,
	ShieldAlert,
	SquarePen,
	SquarePlus,
	Star,
	Table,
	Terminal,
	Trash2,
	UserCog,
	Users,
	Video,
	VideoOff,
	Wrench,
	Zap,
	type LucideProps,
} from 'lucide-react';

const ICONS: Record< string, ComponentType< LucideProps > > = {
	activity: Activity,
	'arrow-up-down': ArrowUpDown,
	bell: Bell,
	'bell-ring': BellRing,
	'book-open': BookOpen,
	bot: Bot,
	bug: Bug,
	'calendar-off': CalendarOff,
	clock: Clock,
	code: Code,
	construction: Construction,
	copy: Copy,
	'corner-up-left': CornerUpLeft,
	'external-link': ExternalLink,
	eye: Eye,
	'eye-off': EyeOff,
	'file-code': FileCode,
	'file-down': FileDown,
	'file-text': FileText,
	folder: Folder,
	'folder-open': FolderOpen,
	gauge: Gauge,
	hash: Hash,
	history: History,
	image: Image,
	'image-down': ImageDown,
	'image-minus': ImageMinus,
	'image-plus': ImagePlus,
	images: Images,
	import: Import,
	inbox: Inbox,
	instagram: Instagram,
	'layout-dashboard': LayoutDashboard,
	'layout-grid': LayoutGrid,
	link: Link,
	'log-in': LogIn,
	mail: Mail,
	'mail-check': MailCheck,
	'mail-open': MailOpen,
	'message-square': MessageSquare,
	'panel-top': PanelTop,
	puzzle: Puzzle,
	'refresh-cw': RefreshCw,
	'refresh-cw-off': RefreshCwOff,
	replace: Replace,
	'search-x': SearchX,
	shield: Shield,
	'shield-alert': ShieldAlert,
	'square-pen': SquarePen,
	'square-plus': SquarePlus,
	star: Star,
	table: Table,
	terminal: Terminal,
	'trash-2': Trash2,
	'user-cog': UserCog,
	users: Users,
	video: Video,
	'video-off': VideoOff,
	wrench: Wrench,
	zap: Zap,
};

/** Renders a module's lucide icon by its meta.json name, Puzzle as fallback. */
export function ModuleIcon( {
	name,
	size = 20,
}: {
	name: string;
	size?: number;
} ): JSX.Element {
	const Icon = ICONS[ name ] ?? Puzzle;
	return <Icon size={ size } aria-hidden />;
}
